{{
    exports.sampleData = [
        ['Zero is Armstrong numbers',                                  0,          true],
        ['Single digits are Armstrong numbers',                        5,          true],
        ['There are no two digit Armstrong numbers',                  10,         false],
        ['Three-digit number that is an Armstrong number',           154,          true],
        ['Three-digit number that is not an Armstrong number',       100,         false],
        ['Four-digit number that is an Armstrong number',           9474,          true],
        ['Four-digit number that is not an Armstrong number',       9475,         false],
        ['A seven digit number that is an Armstrong number',     9926315,          true],
        ['A seven digit number that is not an Armstrong number', 9926314,         false]
    ];
}}

###
# @loop for testCase of sampleData
{{
    httpRegion.metaData.title = testCase[0]
}}
@number = {{testCase[1]}}
@expected = {{testCase[2]}}

/api/armstrong-numbers
    ?number={{number}}

?? status == 200
?? header content-type includes json
?? body isArmstrongNumber isBoolean
?? body isArmstrongNumber equals {{expected}}

### Error when number is not specified
/api/armstrong-numbers

?? status == 400
?? header content-type includes json
?? body message exists
?? body message equals Please pass a number on the query string
